Repository boradesanket13/analog-clock, pull requests merged in 2022-10, with the labels that each got.

#15 Dark mode added with option of theme change
  css/darkwall.jpg
  css/style.css
  index.html
  js/main.js
Labels: hacktoberfest, hacktoberfest-accepted

#16 Create code-of-conduct.md
  code-of-conduct.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#17 Add shadow to clock
  css/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#30 Change numbers color in darkmode to black
  css/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#31 Added Random quote
  css/style.css
  index.html
  js/main.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#38 Moved theme button to top right
  css/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#41 font updated
  css/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#46 Add footer animation
  css/style.css
  index.html
  js/main.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
